only run dep check if exists

diff --git a/.github/workflows/dependency-check.yml b/.github/workflows/dependency-check.yml
--- a/.github/workflows/dependency-check.yml
+++ b/.github/workflows/dependency-check.yml
@@ -34,24 +34,37 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: ./.github/actions/setup-build
+      - name: Check if DEPENDENCIES file exists
+        id: check-if-exists
+        run: |
+          [ ! -f DEPENDENCIES ] && echo "DEPENDENCIES_EXISTS=true" >> $GITHUB_OUTPUT
+          exit 0
+
       - name: Download latest Eclipse Dash
+
         run: |
           curl -L https://repo.eclipse.org/service/local/artifact/maven/redirect\?r\=dash-licenses\&g\=org.eclipse.dash\&a\=org.eclipse.dash.licenses\&v\=LATEST --output dash.jar
       - name: Regenerate DEPENDENCIES
         run: |
-          # dash returns a nonzero exit code if there are libs that need review. the "|| true" avoids that
-          ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq | java -jar dash.jar - -summary DEPENDENCIES-gen || true
-
-          # log warning if restricted deps are found
-          grep -E 'restricted' DEPENDENCIES | if test $(wc -l) -gt 0; then 
-            echo "::warning file=DEPENDENCIES,title=Restricted Dependencies found::Some dependencies are marked 'restricted' - please review them" 
-          fi
-
-          # log error and fail job if rejected deps are found
-          grep -E 'rejected' DEPENDENCIES | if test $(wc -l) -gt 0; then
-            echo "::error file=DEPENDENCIES,title=Rejected Dependencies found::Some dependencies are marked 'rejected', they cannot be used"
-            exit 1
+          if [ -f DEPENDENCIES ]; then
+            # dash returns a nonzero exit code if there are libs that need review. the "|| true" avoids that
+            ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq | java -jar dash.jar - -summary DEPENDENCIES-gen || true
+  
+            # log warning if restricted deps are found
+            grep -E 'restricted' DEPENDENCIES | if test $(wc -l) -gt 0; then 
+              echo "::warning file=DEPENDENCIES,title=Restricted Dependencies found::Some dependencies are marked 'restricted' - please review them" 
+            fi
+  
+            # log error and fail job if rejected deps are found
+            grep -E 'rejected' DEPENDENCIES | if test $(wc -l) -gt 0; then
+              echo "::error file=DEPENDENCIES,title=Rejected Dependencies found::Some dependencies are marked 'rejected', they cannot be used"
+              exit 1
+            fi
+          else
+            echo "::warning file=DEPENDENCIES,title=DEPENDENCIES file missing::The DEPENDENCIES file was missing, the checks did not run."
           fi
       - name: Check for differences
         run: |
-          diff DEPENDENCIES DEPENDENCIES-gen
+          if [ -f DEPENDENCIES ]; then
+            diff DEPENDENCIES DEPENDENCIES-gen
+          fi
